files:
  - source: /*.ts
    translation: /yaryna/translations/%locale%/%original_file_name%
    languages_mapping:
      locale:
        fr: fr
  - source: /*.resx
    translation: /yaryna/translations/%two_letters_code%/%original_file_name%
