files:
  - source: /*.json
    translation: /olga/translations/%locale%.%file_extension%
    languages_mapping:
      locale:
        zh-CN: CH
  - source: /*.po
    translation: /po/trans/%two_letters_code%.%original_file_name%
