files:
  - source: Multilingual_spreadsheet_sample.csv
    translation: /translations/%locale_with_underscore%/%original_file_name%
    multilingual_spreadsheet: '1'
    first_line_contains_header: '1'
    scheme: 'identifier,context,source_phrase,es-ES,fr,max_length'
  - source: Sample.csv
    translation: /translations/%locale_with_underscore%/%original_file_name%
    scheme: 'identifier,source_or_translation'
  - source: '*.xml'
    translation: /translations/%locale%/%original_file_name%
    translate_attributes: '0'
    content_segmentation: '0'
  - source: '*.*'
    ignore:
      - '*.csv'
      - '*.xml'
      - '*.md'
    translation: /translations/%locale%/%original_file_name%
  - source: Example.xml
    translation: /test/%android_code%/%original_file_name%
    content_segmentation: '0'
    translatable_elements:
      - data/string id
